# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GifBoard' do
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod "RxGesture"
  pod 'SwiftyGif'
  pod 'lottie-ios'
  use_frameworks!

  # Pods for GifBoard

  target 'GifBoardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GifBoardUITests' do
    # Pods for testing
  end

end
